### ISSUE TITLE
[TimeSpeed] Incorrect scaling for local coop

### ISSUE THREAD

**Issue by brendangadd** [cantorsdust/TimeSpeed#15]
During local coop, time appears to be over-scaled.
* Seconds per ten minutes above 7 are reported to freeze time.
* Values of 7.01 and 7.013 are reported to map to ~10 and 16 second results.

Taking a look at the code (with no modding experience), I think it could be:
* Extra handler registrations from local player 2
* If SMAPI reports `IsMainPlayer` for both local players
* If SMAPI invokes `UpdateTicked` handlers for each local player
* Contention on `TimeHelper.TickProgress` and the strict equality check on floats
* Any combination of the above

In any case, it sounds like `ScaleTickProgress` is getting called more often than intended and scaling back time to the point that it can never progress to the next milestone.

**Comment by Rahmiel** [comment]
I was actually looking for some reasoning behind this, as it didn't make sense with my basic knowledge of coding, which is very basic, pun not intended. Either way, I thought it might have something to do with both players being local, but I couldn't figure out the math. I'm assuming each call of ScaleTickProgress is exponential with the way this mod works, causing a point where it reaches infinity even though you would assume it is only doubled. Math is fun.

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming TimeSpeed 2.5. Thanks for reporting it!

If you're curious, the issue happened because:
1. In split-screen mode, [each screen runs within the same game instance and events are called for each screen](https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.5#Split-screen_mode).
2. The `UpdateTicked` handler didn't ignore update ticks if received for a farmhand.
3. Since the mod state (including the internal clock) is shared across screens, farmhand updates caused the clock to be incorrectly updated multiple times per tick.

So essentially the fix is adding `if (!this.ShouldEnable()) return;` to the update handler.
