### ISSUE TITLE
Unify mod repositories

### ISSUE THREAD

**Issue by Pathoschild** [cantorsdust/TimeSpeed#5]
Hi @cantorsdust,

Any objections to combining your Stardew Valley mod repositories into one? That makes them easier to maintain and update. If that sounds fine, I'll submit a pull request so you just need to approve it. (I'll also include all the updates to the community editions in the pull request.)

**Comment by Pathoschild** [comment]
(Also, I'll merge them all into this one if you have no objections.)

**Comment by cantorsdust** [comment]
Nope!

**Comment by Pathoschild** [comment]
@cantorsdust Thanks for accepting [my pull request](https://github.com/cantorsdust/TimeSpeed/pull/6)! 

Two followup points:
* I suggest also [renaming the repository](https://github.com/Pathoschild/TimeSpeed/settings) from "TimeSpeed" to "StardewMods".
* I can continue maintaining the repository and mods while you're away if you're interested. If that sounds good, can you [add me as a collaborator](https://github.com/cantorsdust/TimeSpeed/settings/collaboration)? That will let me push updates to the repository, but I won't have access to the settings.

**Comment by cantorsdust** [comment]
That's fine with me. I have 6.5 years remaining in residency and
fellowship, so I don't anticipate returning for some time :)

I might at some point update and upload my minor mods that I never
maintained for public release once this 1.25 update with **cool shit** in
it gets released and I start playing again, but otherwise have at it.

Only two requirements:
1) Please include me as a coauthor when you release stuff.
2) Please keep things open source so that the rest of the modding community
learns from what you do.

Thanks for your work.

**Comment by Pathoschild** [comment]
Those requirements are fine. I'm a big fan of open-source, so no worries on that count; I'll keep your current license. :)
